### ISSUE TITLE
Error: SyntaxError: Expected property name or '}' in JSON at position 1

### ISSUE THREAD

**Issue by salgo60** [skripnik/wikipedia-section-summaries#1]
From the console

<img width="1377" alt="image" src="https://github.com/skripnik/wikipedia-section-summaries/assets/14206509/06332f5c-ab9b-46bc-ad6e-bba6601e51f8">

**Could be that I have added the wrong key how do I add it again?!?!?!**

{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}

**Comment by skripnik** [comment]
Thank you again! I just uploaded an updated script and added settings button. Now in the settings window you can set or change the API key or the engine (if you have access to GPT-4, otherwise keep it GPT-3.5).

**Comment by salgo60** [comment]
Could be my billing plan that is the problem ;-)

<img width="1207" alt="image" src="https://github.com/skripnik/wikipedia-section-summaries/assets/14206509/de50bfff-17ce-47b3-a60f-6a03f08fd439">

**Comment by salgo60** [comment]
@skripnik yes better error msg ;-)

<img width="1207" alt="image" src="https://github.com/skripnik/wikipedia-section-summaries/assets/14206509/daa237da-a4dc-4d8d-8d60-479008d505ee">

**Comment by skripnik** [comment]
Right. Unfortunately, we support now only OpenAI summarization engine that costs money. So far we couldn't find any Open Source models that are good, free and don't require us to run our own server.

P. S. Yes, i just changed a bit error handling, so the error will appear right on the page, not in console. It looks ugly for now. Maybe in the future i'll make better UX for error handling. Thank you for testing and reporting bugs.

**Comment by salgo60** [comment]
Thanks who are we?
* is thus part of any bigger initiative?
    * I would like to see NER on the fly.... pointing on Wikipedia articles see example how [OpenParlTV](https://twitter.com/OpenParlTV) does use [Wikidata for German parlament text](https://twitter.com/OpenParlTV/status/1636316690643406848?s=20)

**Comment by salgo60** [comment]
Cool then you maybe met @dpriskorn [videostar](https://www.youtube.com/live/Nd-kckDEaR0?feature=share&t=5197)

**Comment by skripnik** [comment]
Yeah, I remember that guy :) Our presentation is on the same video on 37:51

**Comment by tonythomas01** [comment]
Also fixed in the fork https://github.com/tonythomas01/wikipedia-section-summaries. Also enabled "Issues" there.

**Comment by salgo60** [comment]
Cool project would be cool to also set your own **prompt to chatGPT and the language**

* **[Act as a](https://datafit.ai/cat/learning)** 
   * [act as an historian](https://datafit.ai/prompt/8674)
* **Improve this**
* create RDF

**Comment by dpriskorn** [comment]
> Thanks who are we?
> * is this part of any bigger initiative?
>     * I would like to see NER on the fly.... pointing on Wikipedia articles see example how [OpenParlTV](https://twitter.com/OpenParlTV) does use [Wikidata for German parlament text](https://twitter.com/OpenParlTV/status/1636316690643406848?s=20)

Internet Archive also uses chatgpt now in a prototype to summarize transcripts of tv recordings. Very interesting work as you can now get an idea of what is reported and how on tv in different countries.

**Comment by salgo60** [comment]
@dpriskorn do you have a link?


I saw something from IA a month ago that was very impressing


Would be cool if IA could add subjects and that we from inside a Wiki article about a topic IA have in its dataset could get a link to the IA app and get an understanding how this subject is mentioned in different countries....
Topics like 
* Ukrainian war
* Covid 
* global warming
* immigration
* gun control
* gender identity
* AI
* freedom of speech and misinformation
* genetic engineering 
* Privacy and Surveillance
* income inequality
*
